export default [
  {
    title: "Matthew Palmer",
    subtitle: "VA Grad / UoB Coding Bootcamp",
    description: "lorem10",
    imageUrl: "https://avatars.githubusercontent.com/u/87938352?v=4",
    gitLink: "https://github.com/tigerbath",
    linkedLink: "https://www.linkedin.com/in/matthew-palmer-a13aab156/",
  },
  {
    title: "Kayle Rieger Paton",
    subtitle: "Massive Legend / UoB Coding Bootcamp",
    description: "working",
    imageUrl: "https://avatars.githubusercontent.com/u/86710295?v=4",
    gitLink: "https://github.com/kayleriegerpatton",
    linkedLink: "http://www.linkedin.com/in/kaylerieger",
  },
  {
    title: "Conor Kelly",
    subtitle: "Massive Legend / UoB Coding Bootcamp",
    description: "lorem10",
    imageUrl: "https://avatars.githubusercontent.com/u/65548530?v=4",
    gitLink: "https://github.com/conorjkelly96/",
    linkedLink: "https://linkedin.com/in/conorjkelly96",
  },
  {
    title: "Sumaia Sorna",
    subtitle: "Massive Legend / UoB Coding Bootcamp",
    description: "lorem10",
    imageUrl: "https://avatars.githubusercontent.com/u/89305781?v=4",
    gitLink: "https://github.com/SumaiaSorna",
    linkedLink: "",
  },
  {
    title: "Yashemabeth Mcleod",
    subtitle: "Massive Legend / UoB Coding Bootcamp",
    description: "lorem10",
    imageUrl: "https://avatars.githubusercontent.com/u/79544778?v=4",
    gitLink: "https://github.com/Yashemabeth",
    linkedLink: "",
  },
  {
    title: "Liana Laurentiu",
    subtitle: "Massive Legend / UoB Coding Bootcamp",
    description: "lorem10",
    imageUrl: "https://avatars.githubusercontent.com/u/77942076?v=4",
    gitLink: "https://github.com/lianavaleria15",
    linkedLink: "",
  },
];
